version: '3.1'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ilovepasswords
  
  lighthouse:
    image: spotify/lighthouse-audit-service:latest
    environment:
      PGHOST: db
      PGUSER: postgres
      PGPASSWORD: ilovepasswords
      LAS_PORT: 4008
      LAS_CORS: true
    ports:
      - "4008:4008"
