site_name: 'example-docs'
site_description: 'Lorem ipsum odor amet'
plugins:
  - techdocs-core
nav:
  - Getting Started: index.md
  - Section 1:
    - compose: compose.md
    - compose_cp: compose_cp.md
    - compose_port: compose_port.md
    - compose_stop: compose_stop.md
    - compose_alpha: compose_alpha.md
    - compose_create: compose_create.md
    - compose_ps: compose_ps.md
    - compose_top: compose_top.md
    - compose_alpha_dry: compose_alpha_dry-run.md
    - compose_down: compose_down.md
    - compose_pull: compose_pull.md
  - Section 2:
    - compose_unpause: compose_unpause.md
    - compose_alpha_publish: compose_alpha_publish.md
    - compose_events: compose_events.md
    - compose_push: compose_push.md
    - compose_up: compose_up.md
    - compose_alpha_scale: compose_alpha_scale.md
    - compose_exec: compose_exec.md
    - compose_restart: compose_restart.md
    - compose_version: compose_version.md
    - compose_alpha_viz: compose_alpha_viz.md
    - compose_images: compose_images.md
    - compose_rm: compose_rm.md
    - compose_wait: compose_wait.md
    - compose_alpha_watch: compose_alpha_watch.md
    - compose_kill: compose_kill.md
    - compose_run: compose_run.md
  - Section 3:
    - compose_watch: compose_watch.md
    - compose_attach: compose_attach.md
    - compose_logs: compose_logs.md
    - compose_scale: compose_scale.md
    - compose_build: compose_build.md
    - compose_ls: compose_ls.md
    - compose_start: compose_start.md
    - compose_config: compose_config.md
    - compose_pause: compose_pause.md
    - compose_stats: compose_stats.md
